-- ============================================================
-- NIF - SCHÉMA DE RÉFÉRENCE (documentation uniquement)
--
-- ⚠️ NE PAS EXÉCUTER : ces tables existent déjà, créées par les
-- migrations Django (`python manage.py migrate`). Ce fichier sert
-- uniquement à documenter la vraie structure actuelle de la base,
-- en remplacement de l'ancien nif.sql (schéma pré-Django, obsolète).
--
-- Toute modification de structure doit passer par users/models.py
-- puis `python manage.py makemigrations` / `migrate` — jamais par
-- un ALTER TABLE ou CREATE TABLE manuel, sous peine de désynchroniser
-- la base et l'historique des migrations (voir l'incident du champ
-- password, qui a nécessité un correctif manuel).
--
-- Différences principales avec l'ancien nif.sql :
--   - operateur a bien propr_name/last_name (nif.sql ne les avait pas)
--   - la table des messages contribuable s'appelle "messages" (pluriel),
--     avec les colonnes prenif/question/reponse (nif.sql décrivait une
--     table "message" au singulier, avec une structure différente)
--   - les clés étrangères portent un suffixe "_id" (convention Django),
--     ex. logiciel_id, nimp_id, id_contribuable_id, central_recette_id,
--     mode_paiement_id — nif.sql ne l'avait pas
--   - civisme_fiscale, auth_token_contribuable, verification_code
--     n'existaient pas dans nif.sql
--   - le géo-découpage (country/parish/city/locality/wereda/fokontany)
--     et operateurs/activity/users_nif/etc. de nif.sql ne sont PAS
--     gérés par l'application actuelle (modèles Django absents)
-- ============================================================


-- ------------------------------------------------------------
-- Référentiels
-- ------------------------------------------------------------
-- genre(id, genre)
-- logiciel(id, logiciel)                         -- SURF / SIGTAS / HETRAONLINE
-- mode_paiement(id, sens)                        -- espece / virement / depot / declaration
-- num_impot(id, impot, numero)                   -- IRSA=5, IR=10, IS=15, AMENDE=43, PENALITE=44

-- ------------------------------------------------------------
-- Opérateurs (source de vérité pour l'inscription)
-- ------------------------------------------------------------
-- operateur(
--     id               SERIAL PRIMARY KEY,        -- pas "id_operateur"
--     propr_cin        VARCHAR(220),
--     propr_contact    VARCHAR(220),
--     propr_name       VARCHAR(100),               -- absent de l'ancien nif.sql
--     last_name        VARCHAR(100)                -- absent de l'ancien nif.sql
-- );

-- ------------------------------------------------------------
-- Contribuables
-- ------------------------------------------------------------
-- contribuable(
--     id_contribuable    SERIAL PRIMARY KEY,
--     create_date        DATE NOT NULL,             -- auto_now_add côté Django
--     dm_cin             VARCHAR(15),
--     propr_name         VARCHAR(100),
--     last_name          VARCHAR(100),
--     sex                INTEGER,                   -- 1=Homme, 2=Femme (choices, PAS de FK vers genre)
--     birth_date         DATE,
--     birth_place        VARCHAR(120),
--     sit_matrim         INTEGER,                   -- 1..4 (choices, PAS de FK)
--     propr_cin          VARCHAR(15),
--     delivr_cin_date    DATE,
--     cin_place          VARCHAR(120),
--     propr_contact      VARCHAR(14),
--     mailing_address    VARCHAR(200),
--     bank_acct_no       VARCHAR(250),
--     passeport          VARCHAR(20),
--     dm_ref             VARCHAR(15),
--     propr_prenif       VARCHAR(10),
--     statistic_no       VARCHAR(21),
--     statistic_date     DATE,
--     fkt_no             DATE,                      -- anomalie du modèle : DateField, pas une FK Fokontany
--     password           VARCHAR(128),              -- corrigé manuellement depuis 20 ; à aligner dans models.py
--     photo              VARCHAR(200)
-- );

-- ------------------------------------------------------------
-- Transactions et paiements
-- ------------------------------------------------------------
-- central_recette(
--     id_transaction       SERIAL PRIMARY KEY,
--     id_contribuable_id   INTEGER REFERENCES contribuable(id_contribuable),
--     id_centre_recette    VARCHAR(200),
--     regisseur            VARCHAR(50),
--     logiciel_id          INTEGER REFERENCES logiciel(id),
--     ref_trans            VARCHAR(60),
--     ref_reglement        VARCHAR(60),
--     daty                 DATE,
--     mouvement            VARCHAR(1) DEFAULT '0',
--     moyen_paiement       VARCHAR(2),
--     rib                  VARCHAR(30),
--     prenif               VARCHAR(20),
--     raison_sociale       VARCHAR(250),
--     nimp_id              INTEGER REFERENCES num_impot(id),
--     numrec               INTEGER,
--     libelle              VARCHAR(20),
--     flag                 VARCHAR(1) DEFAULT 'N',
--     date_debut           DATE,
--     date_fin             DATE,
--     periode              INTEGER DEFAULT 1,
--     periode2             VARCHAR(10),
--     mnt_ap               DOUBLE PRECISION,
--     base                 DOUBLE PRECISION,
--     imp_detail           VARCHAR(200),
--     da                   INTEGER DEFAULT 0,
--     banque               VARCHAR(75),
--     annee_recouvrement   INTEGER,
--     code_bureau          VARCHAR(250),
--     libelle_bureau       VARCHAR(250)
-- );

-- paiement(
--     id                   SERIAL PRIMARY KEY,       -- absent de l'ancien nif.sql (pas de PK explicite)
--     id_contribuable_id   INTEGER,
--     central_recette_id   INTEGER REFERENCES central_recette(id_transaction),
--     mode_paiement_id     INTEGER REFERENCES mode_paiement(id),
--     n_quit               VARCHAR(50),
--     montant              DOUBLE PRECISION,
--     date_paiement        DATE                       -- auto_now_add côté Django
-- );

-- ------------------------------------------------------------
-- Messages (contribuable <-> service d'aide)
-- ------------------------------------------------------------
-- messages(                                          -- PAS "message" (singulier) comme dans nif.sql
--     id               SERIAL PRIMARY KEY,
--     prenif           TEXT,                          -- texte libre, pas de FK vers contribuable
--     question         TEXT,
--     reponse          TEXT,
--     date_question    TIMESTAMP,                      -- auto_now_add
--     date_reponse     TIMESTAMP                        -- auto_now_add (anomalie : se remplit à la création)
-- );

-- ------------------------------------------------------------
-- Civisme fiscal (absent de l'ancien nif.sql)
-- ------------------------------------------------------------
-- civisme_fiscale(
--     id             SERIAL PRIMARY KEY,
--     video          BYTEA,
--     description    TEXT,
--     question       TEXT,
--     reponse        TEXT,
--     quizz          JSONB
-- );

-- ------------------------------------------------------------
-- ------------------------------------------------------------
-- auth_token_contribuable(
-- Authentification (ajoutée depuis nif.sql, pas d'équivalent d'origine)
--     key              VARCHAR(64) PRIMARY KEY,
--     contribuable_id  INTEGER REFERENCES contribuable(id_contribuable),
--     created          TIMESTAMP,
--     expires          TIMESTAMP
-- );

-- verification_code(
--     id               SERIAL PRIMARY KEY,
--     contribuable_id  INTEGER REFERENCES contribuable(id_contribuable),
--     purpose          VARCHAR(10),                    -- 'login' ou 'reset'
--     code_hash        VARCHAR(128),
--     created          TIMESTAMP,
--     attempts         SMALLINT DEFAULT 0,
--     used             BOOLEAN DEFAULT FALSE
-- );

-- ------------------------------------------------------------
-- Vues (voir sql/vues.sql pour le code exécutable)
-- ------------------------------------------------------------
-- vue_messages
-- vue_somme_par_contribuable_par_annee
-- vue_detail_transactions_par_quit_et_contribuable