# Generated by Django 5.0.6 on 2024-11-07 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
                ('city_name_f', models.CharField(max_length=25)),
                ('city_name_s', models.CharField(max_length=25)),
                ('city_code', models.CharField(max_length=5)),
                ('city_name_extra', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CivismeFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.BinaryField()),
                ('description', models.TextField()),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('quizz', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id_contribuable', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('dm_cin', models.CharField(blank=True, max_length=15, null=True)),
                ('propr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Homme'), (2, 'Femme')], null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=120, null=True)),
                ('sit_matrim', models.IntegerField(blank=True, choices=[(1, 'Célibataire'), (2, 'Marié(e)'), (3, 'Divorcé(e)'), (4, 'Veuf(ve)')], null=True)),
                ('propr_cin', models.CharField(blank=True, max_length=15, null=True)),
                ('delivr_cin_date', models.DateField(blank=True, null=True)),
                ('cin_place', models.CharField(blank=True, max_length=120, null=True)),
                ('propr_contact', models.CharField(blank=True, max_length=14, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_acct_no', models.CharField(blank=True, max_length=250, null=True)),
                ('passeport', models.CharField(blank=True, max_length=20, null=True)),
                ('dm_ref', models.CharField(blank=True, max_length=15, null=True)),
                ('propr_prenif', models.CharField(blank=True, max_length=10, null=True)),
                ('statistic_no', models.CharField(blank=True, max_length=21, null=True)),
                ('statistic_date', models.DateField(blank=True, null=True)),
                ('fkt_no', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$', 'Le mot de passe doit contenir au moins une lettre et un chiffre.')])),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'contribuable',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_name_f', models.CharField(max_length=20)),
                ('country_name_s', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=4)),
                ('capital', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=220)),
                ('contact', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='SituationMatrimoniale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_desc', models.CharField(max_length=30)),
                ('locality_desc_f', models.CharField(max_length=30)),
                ('locality_desc_s', models.CharField(max_length=30)),
                ('locality_code', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=35)),
                ('parish_name_f', models.CharField(max_length=35)),
                ('parish_name_s', models.CharField(max_length=35)),
                ('parish_code', models.CharField(max_length=4)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parish'),
        ),
        migrations.CreateModel(
            name='Wereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wereda_desc', models.CharField(max_length=50)),
                ('wereda_code', models.IntegerField()),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkt_desc', models.CharField(max_length=500)),
                ('wereda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.wereda')),
            ],
        ),
    ]
