# Generated by Django 5.1.3 on 2024-12-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contribuable', models.IntegerField()),
                ('n_quit', models.CharField(max_length=50)),
                ('date_paiement', models.DateField()),
                ('annee_de_paiement', models.IntegerField()),
                ('annee_recouvrement', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mnt_ap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nimp', models.IntegerField()),
                ('imp_detail', models.TextField()),
                ('numero', models.CharField(max_length=50)),
                ('impot', models.CharField(max_length=50)),
                ('sens', models.CharField(max_length=50)),
                ('logiciel', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vue_detail_transactions_par_quit_et_contribuable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueSommeParContribuableParAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuable', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('total_mnt_ver', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vue_somme_par_contribuable_par_annee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logiciel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'logiciel',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenif', models.TextField()),
                ('question', models.TextField()),
                ('reponse', models.TextField(blank=True, null=True)),
                ('date_question', models.DateTimeField()),
                ('date_reponse', models.DateTimeField()),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mode_paiement',
            },
        ),
        migrations.CreateModel(
            name='NumImpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impot', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'num_impot',
            },
        ),
        migrations.RenameField(
            model_name='operateur',
            old_name='cin',
            new_name='propr_cin',
        ),
        migrations.RenameField(
            model_name='operateur',
            old_name='contact',
            new_name='propr_contact',
        ),
        migrations.AddField(
            model_name='operateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operateur',
            name='propr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='civismefiscale',
            table='civisme_fiscale',
        ),
        migrations.AlterModelTable(
            name='operateur',
            table='operateur',
        ),
        migrations.CreateModel(
            name='CentralRecette',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('id_centre_recette', models.CharField(max_length=200)),
                ('regisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_trans', models.CharField(max_length=60)),
                ('ref_reglement', models.CharField(max_length=60)),
                ('daty', models.DateField()),
                ('mouvement', models.CharField(default='0', max_length=1)),
                ('moyen_paiement', models.CharField(blank=True, max_length=2, null=True)),
                ('rib', models.CharField(blank=True, max_length=30, null=True)),
                ('prenif', models.CharField(blank=True, max_length=20, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=250, null=True)),
                ('numrec', models.IntegerField()),
                ('libelle', models.CharField(max_length=20)),
                ('flag', models.CharField(default='N', max_length=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('periode', models.IntegerField(default=1)),
                ('periode2', models.CharField(blank=True, max_length=10, null=True)),
                ('mnt_ap', models.FloatField()),
                ('base', models.FloatField()),
                ('imp_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('da', models.IntegerField(default=0)),
                ('banque', models.CharField(blank=True, max_length=75, null=True)),
                ('annee_recouvrement', models.IntegerField()),
                ('code_bureau', models.CharField(max_length=250)),
                ('libelle_bureau', models.CharField(max_length=250)),
                ('id_contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contribuable')),
                ('logiciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.logiciel')),
                ('nimp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.numimpot')),
            ],
            options={
                'db_table': 'central_recette',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_quit', models.CharField(max_length=50)),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('central_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.centralrecette')),
                ('id_contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contribuable')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modepaiement')),
            ],
            options={
                'db_table': 'paiement',
            },
        ),
    ]
