# Generated by Django 6.1 on 2026-09-19 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transactionview_vuesommeparcontribuableparannee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuable', models.IntegerField()),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
                ('propr_prenif', models.CharField(max_length=50)),
                ('propr_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('questions', models.TextField()),
                ('reponses', models.TextField()),
                ('date_reponse', models.DateField()),
                ('date_question', models.DateField()),
            ],
            options={
                'db_table': 'vue_messages',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$', 'Le mot de passe doit contenir au moins une lettre, un chiffre, et un caractère spécial parmi @$!%*?&.')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_question',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_reponse',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.contribuable')),
            ],
            options={
                'db_table': 'auth_token_contribuable',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Connexion'), ('reset', 'Mot de passe oublié')], max_length=10)),
                ('code_hash', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='users.contribuable')),
            ],
            options={
                'db_table': 'verification_code',
            },
        ),
    ]
