
# Generated by Django 6.1 on 2026-09-28 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_messagesadmin_alter_contribuable_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribuable',
            old_name='sex',
            new_name='sexe',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$', 'Le mot de passe doit contenir au moins une lettre, un chiffre, et un caractère spécial parmi @$!%*?&.')]),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='contribuable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='users.contribuable'),
        ),
    ]
