# Generated by Django 6.1 on 2026-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_sex_contribuable_sexe_verificationcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civismefiscale',
            name='quizz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
