# Generated by Django 6.1 on 2026-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_civismefiscale_quizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
